### ISSUE TITLE
Demo site link is "404 not found"

### ISSUE THREAD

**Issue by impressivewebs** [bobbymannino/svelte-toaster#2]
https://bobbymannino.vercel.app/svelte-toaster

It should be:

https://bobbymannino.vercel.app/npm-packages/svelte-toaster

**Comment by impressivewebs** [comment]
@bobbymannino FYI - the "About" section in the sidebar where the URL is still includes the 404 link.

**Comment by bobbymannino** [comment]
thank you for spotting this!
